using MediatR;
using PortfolioPerformance.Api.Features.Portfolio.DTO.Request;
using PortfolioPerformance.Api.Features.Portfolio.DTO.Response;
using PortfolioPerformance.Api.Infrastructure.Contracts;
using PortfolioPerformance.Data.Contracts;

namespace PortfolioPerformance.Api.Features.Portfolio.Handlers
{
    public class CreatePortfolio
    {
        public class EndPoint : IEndpoint
        {
            public void Configure(IEndpointRouteBuilder app)
            {
                app.MapPost("/api/portfolio", async (CreatePortfolioDto request, ISender _sender) =>
                {
                    return Results.Ok(await _sender.Send(new CreatePortfolioCommand(request)));
                })
                .WithName("CreatePortfolio")
                .WithTags("Portfolio");
            }
        }

        public record CreatePortfolioCommand(CreatePortfolioDto Request) : IRequest<CreatePortfolioResponse>
        {
            public CreatePortfolioDto Portfolio { get; init; } = Request;
        }


        public class Handler(IPortfolioPerformanceRepository<Data.Entities.Portfolio> _repository) : IRequestHandler<CreatePortfolioCommand, CreatePortfolioResponse>
        {
            public async Task<CreatePortfolioResponse> Handle(CreatePortfolioCommand request, CancellationToken cancellationToken)
            {
                await _repository.AddAsync(new Data.Entities.Portfolio
                {
                    Name = request.Portfolio.Name,
                    Description = request.Portfolio.Description
                });


                return await Task.FromResult(new CreatePortfolioResponse
                {
                    Id = Guid.NewGuid(), // Assuming the ID is generated by the database
                    Name = request.Portfolio.Name,
                    Description = request.Portfolio.Description
                });
            }
        }
    }
}
